# version: 2.1
# setup: true
# orbs:
#   build: mojaloop/build@1.0.55
# workflows:
#   setup:
#     jobs:
#       - build/workflow:
#           filters:
#             tags:
#               only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
#           # optionally supply the base image for the image scan
#           base_image: node:18-alpine
version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: testcafe/testcafe:latest
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            apk update
            apk add --no-cache yarn bash chromium chromium-chromedriver xvfb dbus-x11 ttf-freefont font-noto git docker-cli docker-compose
            yarn --version
      - run:
          name: Set Chrome Binary Path
          command: |
            export CHROME_BIN=/usr/bin/chromium-browser
            export CHROME_PATH=/usr/lib/chromium/
            export BROWSER_TCAFE=chromium:headless
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Integration Tests
          command: |
            mkdir -p /tmp/test-results
            yarn test:integration
          environment:
            CHROME_BIN: /usr/bin/chromium-browser
            CHROME_PATH: /usr/lib/chromium/
            BROWSER_TCAFE: chromium:headless
            DISPLAY: :99
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results/test-report.html
workflows:
  e2e-test:
    jobs:
      - test