# version: 2.1
# setup: true
# orbs:
#   build: mojaloop/build@1.0.55
# workflows:
#   setup:
#     jobs:
#       - build/workflow:
#           filters:
#             tags:
#               only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
#           # optionally supply the base image for the image scan
#           base_image: node:18-alpine
version: 2.1
orbs:
  node: circleci/node@4.1.0
executors:
  default-machine:
    working_directory: /home/circleci/project
    shell: "/bin/bash -leo pipefail"
    machine:
      image: ubuntu-2204:2023.04.2
jobs:
  test:
    executor: default-machine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # Install required tools
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg
            
            # Add Docker's official GPG key
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            
            # Add Docker repository
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            
            # Add Chrome repository
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            
            # Update package lists
            sudo apt-get update
            
            # Install packages
            sudo apt-get install -y yarn chromium-browser chromium-chromedriver xvfb dbus-x11 ttf-freefont fonts-noto git docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            yarn --version
      - run:
          name: Set Chrome Binary Path
          command: |
            export CHROME_BIN=/usr/bin/chromium-browser
            export CHROME_PATH=/usr/lib/chromium/
            export BROWSER_TCAFE=chromium:headless
            export DISPLAY=:99
            Xvfb :99 -screen 0 1024x768x16 &
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Integration Tests
          command: |
            git clone https://github.com/Ujjwal-Izyane/on-premise-deploy-fx
            cd on-premise-deploy-fx
            git checkout 74346ad
            cd docker-compose
            chmod 644 prometheus.yml
            sed -i '/prometheus:/,/^[[:space:]]*$/d' docker-compose.yaml
            env PM4ML_ENABLED=true docker-compose --profile portal up -d
            mkdir -p /tmp/test-results
            yarn test:integration
          environment:
            CHROME_BIN: /usr/bin/chromium-browser
            CHROME_PATH: /usr/lib/chromium/
            BROWSER_TCAFE: chromium:headless
            DISPLAY: :99
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results/test-report.html
workflows:
  e2e-test:
    jobs:
      - test