version: '3'
#
#  Component arrangement is as below:
#
#  ┌────────────┐    ┌────────────┐   ┌─────────────┐    ┌──────────┐
#  │            │    │            │   │             │    │          │
#  │ Simulator  ├───►│ Simulator  ├──►│  Mojaloop   ├───►│  Switch  │
#  │ Backend    │    │   Core     │   │  Connector  │    │          │
#  │            │◄───┤ Connector  │◄──┤             │◄───┤          │
#  └────────────┘    └────────────┘   └─────────────┘    └──────────┘
#

services:

  frontend:
    build: ../../
    environment:
      - API_BASE_URL=http://localhost:4010
    ports:
       - "8081:8080"
    depends_on:
      - experience-api

  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
      - KEYCLOAK_IMPORT=/tmp/pm4ml-realm.json
#      - DB_VENDOR=postgres
#      - DB_ADDR=keycloak-postgresql
#      - DB_PORT=5432
#      - DB_DATABASE=keycloak
#      - DB_USER=keycloak
#      - DB_PASSWORD={{ CHANGE BEFORE INSTALL }}
    volumes:
      - ./keycloak-realm.json:/tmp/pm4ml-realm.json
    ports:
      - "8080:8080"
#    depends_on:
#      - keycloak-postgres

#  keycloak-postgres:
#    image: bitnami/postgresql:11.12.0-debian-10-r23

  experience-api:
    image: pm4ml/mojaloop-payment-manager-experience-api:2.0.2
    ports:
      - "4010:3000"
    environment:
      - APP_KEYS={{ CHANGE BEFORE INSTALL e.g. ootu1yoo5geeS7izai4ox1Yae1Eey6ai}}
      - AUTH_CLIENT_ID=pm4ml-customer-ui
      - AUTH_CLIENT_SECRET=a857e3d7-ebd4-4451-aabd-bcb480dde1a3
      - AUTH_DISCOVERY_ENDPOINT=http://keycloak:8080/auth/realms/pm4ml/.well-known/openid-configuration
      - AUTH_LOGGED_IN_LANDING_URL=http://localhost:8081/
      - AUTH_REDIRECT_NAME=pm4ml-customer-ui
      - AUTH_REDIRECT_URI=http://localhost:4010/auth
      - AUTH_RESOURCE_NAME=pm4ml-customer-ui
      - AUTH_SCOPES=roles
      - DFSP_ID={{ CHANGE BEFORE INSTALL }}
      - ENV_ID=1
      - MANAGEMENT_ENDPOINT=management-api:9000
      - METRICS_ENDPOINT=prometheus:9090
      - MOCK_DATA=false
      - SESSION_REDIS_URL=redis://redis/2
      - SESSION_SECURE=false
    depends_on:
      - management-api
      - keycloak
      - redis

  management-api:
    image: pm4ml/mojaloop-payment-manager-management-api:3.0.10
    environment:
      - AUTH_ENABLED=false
      - AUTH_PASS=pm4mltest123
      - AUTH_USER=pm4mltest
      - CACHE_HOST=redis
      - CACHE_SYNC_INTERVAL_SECONDS=10
      - DFSP_CA_PATH=/secrets
      - DFSP_CA_PATH=/tlsServerCA.pem
      # - DFSP_CLIENT_CSR_PARAMETERS=/resources/tlsClientCSRParameters.json
      - DFSP_CSR_KEY=a
      - DFSP_ID=dfsp1
      # - DFSP_SERVER_CSR_PARAMETERS=/resources/tlsServerCSRParameters.json
      - ENV_ID=1
      - MCM_API_TOKEN={{ REQUIRED BEFORE INSTALL }}
      - MCM_CLIENT_REFRESH_INTERVAL=180000
      - MCM_CLIENT_SECRETS_LOCATION=/secrets
      - MCM_SERVER_ENDPOINT=localhost:9001
      - P12_PASS_PHRASE=SOME_S3C4R3_P@SS
      - PK_SECRETS_LOCATION=/secrets
      - PRIVATE_KEY_ALGORITHM=rsa
      - PRIVATE_KEY_LENGTH=4096
      - TLS_SERVER_PRIVATE_KEY=/tlsServerPvtKey.key
      - TLS_SERVER_PRIVATE_KEY=a
      - WS_PORT=4003
      - WS_URL=mojaloop-connector
      - dfspCsrPrivateKeyAlgorithm=rsa
      - dfspCsrPrivateKeyLength=4096
      - p12PassPhrase=SOME_S3C4R3_P@SS
      - tlsClientCSRParametersPath=/resources/tlsClientCSRParameters.json
      - tlsServerCAPath=/tlsServerCA.pem
      - tlsServerCSRParametersPath=/resources/tlsServerCSRParameters.json
      - tlsServerPvtKeyPath=/tlsServerPvtKey.key
      - VAULT_ENDPOINT=http://172.17.0.1:8233
      - VAULT_PKI_BASE_DOMAIN=example.com
      - VAULT_AUTH_METHOD=APP_ROLE
      - VAULT_ROLE_ID_FILE=.vault/role-id
      - VAULT_ROLE_SECRET_ID_FILE=.vault/secret-id
    volumes:
      - "/tmp/secrets:/secrets"
      - ./.vault:/.vault
    depends_on:
      - redis
      - keycloak
      - mojaloop-connector

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  simulator-core-connector:
    # image: pm4ml/mojaloop-payment-manager-simulator-core-connector:1.4.5
    image: pm4ml/wallet-core-connector:1.0.11
    environment:
      - BACKEND_ENDPOINT=http://sim-backend:3000
      - MLCONN_OUTBOUND_ENDPOINT=http://mojaloop-connector:4001
    ports:
       - "3003:3003"
    depends_on:
      - mojaloop-connector
      - sim-backend

#   core-connector:
#     image: pm4ml/dgto-pm4ml-core-connector:0.0.20
#     environment:
#       - BACKEND_ENDPOINT=http://sim-backend:3002
#       - MLCONN_OUTBOUND_ENDPOINT=http://mojaloop-connector:4001
#     ports:
#        - "3003:3003"
#     extra_hosts:
#       - "dgtof-saccos.co.tz:192.168.10.110"
#     depends_on:
#       - mojaloop-connector
#       - sim-backend

  sim-backend:
    image: "mojaloop/mojaloop-simulator:v11.3.0"
    environment:
      - CA_CERT_PATH=./secrets/cacert.pem
      - DFSP_ID=dfsp1
      - FEE_MULTIPLIER=0.0
      - HTTPS_ENABLED=false
      - LOG_INDENT=0
      - MODEL_DATABASE=./model.sqlite
      - MUTUAL_TLS_ENABLED=false
      - OUTBOUND_ENDPOINT=http://simulator-core-connector:4001
      - REPORT_API_LISTEN_PORT=3002
      # - RULES_FILE=../rules/rules.json
      - SERVER_CERT_PATH=./secrets/servercert.pem
      - SERVER_KEY_PATH=./secrets/serverkey.pem
      - SIMULATOR_API_LISTEN_PORT=3000
      - SQLITE_LOG_FILE=./log.sqlite
      # - SQLITE_LOG_FILE=":memory:"
      - TEST_API_LISTEN_PORT=3003

  redis:
    image: redis:6.2.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_TLS_ENABLED=no

  mojaloop-connector:
    image: pm4ml/mojaloop-connector:14.1.1
    environment:
      - AUTO_ACCEPT_PARTY=false
      - AUTO_ACCEPT_QUOTES=false
      - BACKEND_ENDPOINT=simulator-core-connector:3003
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - DFSP_ID=dfsp1
      - ENABLE_TEST_FEATURES=true
      - INBOUND_LISTEN_PORT=4000
      - INBOUND_MUTUAL_TLS_ENABLED=false
      - IN_CA_CERT_PATH=/secrets/inbound-cacert.pem
      - IN_SERVER_CERT_PATH=/secrets/inbound-cert.pem
      - IN_SERVER_KEY_PATH=/secrets/inbound-key.pem
      - JWS_SIGN=false
      - JWS_SIGNING_KEY_PATH=/jwsSigningKey.key
      - JWS_VERIFICATION_KEYS_DIRECTORY=/jwsVerificationKeys
      - METRICS_SERVER_LISTEN_PORT=4004
      - MULTIPLE_PARTIES_RESPONSE=false
      - MGMT_API_WS_URL=management-api
      - OUTBOUND_LISTEN_PORT=4001
      - OUTBOUND_MUTUAL_TLS_ENABLED=false
      - OUT_CA_CERT_PATH=/secrets/outbound-cacert.pem
      - OUT_CLIENT_CERT_PATH=/secrets/outbound-cert.pem
      - OUT_CLIENT_KEY_PATH=/secrets/outbound-key.pem
      - PEER_ENDPOINT=mojaloop-testing-toolkit:5000
      - TEST_CA_CERT_PATH=/secrets/test-cacert.pem
      - TEST_CLIENT_CERT_PATH=/secrets/test-cert.pem
      - TEST_CLIENT_KEY_PATH=/secrets/test-key.pem
      - TEST_LISTEN_PORT=4002
      - TEST_MUTUAL_TLS_ENABLED=false
      - WS_PORT=4003
      # - OAUTH_TOKEN_ENDPOINT={{ CHANGE BEFORE INSTALL e.g. https://extgw.dev.product.mbox-dev.io:9443/oauth2/token }}
      # - OAUTH_CLIENT_KEY={{ CHANGE BEFORE INSTALL e.g. k9edbgS09cE9qAkiVEaz5Hmuc5Ua }}
      # - OAUTH_CLIENT_SECRET={{ CHANGE BEFORE INSTALL e.g. UvMTwwj7am2agjkAfvmElNte4ewa }}
      - VALIDATE_INBOUND_JWS=false
      - RESERVE_NOTIFICATION=false
      # - RESOURCE_VERSIONS="transfers=1.1"
    ports:
      - "4000:4000"
    volumes:
      - ./outbound-cacert.pem:/secrets/outbound-cacert.pem
      - ./outbound-cert.pem:/secrets/outbound-cert.pem
      - ./outbound-key.pem:/secrets/outbound-key.pem
      - ./inbound-cacert.pem:/secrets/inbound-cacert.pem
      - ./inbound-cert.pem:/secrets/inbound-cert.pem
      - ./inbound-key.pem:/secrets/inbound-key.pem
    depends_on:
      - redis

  mojaloop-testing-toolkit:
    #docker exec -it mojaloop-testing-toolkit npm run cli -- outbound -i collections/payer-tests/sendmoney_error.json -e environments/environment.json
    #docker exec -it mojaloop-testing-toolkit npm run cli -- outbound -i collections/payer-tests/sendmoney.json -e environments/environment.json
    container_name: mojaloop-testing-toolkit
    image: mojaloop/ml-testing-toolkit:v14.0.2
    volumes:
      - "../testing-toolkit/docker-compose/as-a-switch/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "../testing-toolkit/collections:/opt/mojaloop-testing-toolkit/collections"
      - "../testing-toolkit/environments:/opt/mojaloop-testing-toolkit/environments"
    ports:
      - "5000:5000"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"

  mojaloop-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v13.5.3
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

networks:
  default:
    name: payment-manager

